POST http://vaibhav-fast-sample-django-naming.relevel.svc.cluster.local/polls/add_question
Content-Type: application/json

{
  "question_text": "Is Bojack more horse than man?"
}

###
GET http://vaibhav-fast-sample-django-naming.relevel.svc.cluster.local/polls
Accept: application/json

###

